# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GzvoprlpBBeu8SDuVWfIb9ulsB1aWge_
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
import warnings
warnings.filterwarnings('ignore')

data=pd.read_csv("/content/spotify.csv.zip")

data.head()

data.tail()

data.shape

data.info()

data['energy'].dtypes

data['loudness'].dtypes

data['track_id'].dtypes

data['track_id'].dtypes=='O'

data.columns

cat_col=[fea for fea in data.columns if data[fea].dtypes=='O']

data[cat_col]

num_col=[fea for fea in data.columns if data[fea].dtype == 'O']

data[num_col]

data.memory_usage()

data.isnull().sum()

data.isnull().sum().sum()

data.duplicated().sum()

data.nunique()

data['track_id'].unique()

sns.distplot(data['energy'])

data.columns

data['average']=(data['energy']+data['loudness']+data['instrumentalness'])

data.head()

data.groupby('energy')

data.groupby('energy').count()

sns.boxplot(data['loudness'])

sns.boxplot(data['liveness'])

sns.distplot(data['energy'])

